services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - portainer_networks
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
