volumes:
  dvwa:
networks:
  dvwa:
services:
  dvwa:
    build: .
    image: ghcr.io/digininja/dvwa:latest
    pull_policy: always
    environment:
      - DB_SERVER=db
    depends_on:
      - db

    networks:
      - vuln_network
    ports:
      - 127.0.0.1:4281:80

    restart: unless-stopped

  db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa:/var/lib/mysql
    networks:
      - vuln_network
    restart: unless-stopped
    
networks:
  vuln_network:
    driver: bridge