version: "3.9"
services:
  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    networks:
      - vuln_network

networks:
  vuln_network:
    driver: bridge
